name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ec2-13-51-69-79.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@ec2-13-51-69-79.eu-north-1.compute.amazonaws.com "echo SSH connection successful"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-51-69-79.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi-book-project || exit 1
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # Ensure Docker is running
            sudo systemctl restart docker

            # Rebuild and restart the application
            sudo docker-compose down
            sudo docker-compose up --build -d --remove-orphans
